# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('blurb', models.TextField()),
                ('description', models.TextField()),
                ('categories', models.TextField()),
                ('location', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
