# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0002_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
    ]
