# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0003_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='/Users/Kriti/createathon/letsgo/media'),
        ),
    ]
