# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo', '0004_auto_20170506_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
